<a href="https://colab.research.google.com/github/Langston-Wang01/NVIDIA-IGNITE-CV-PROJECT/blob/main/July_28th%2C_2026_Numpy_Challenges.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Challenge 1
# Create a 2D array of random integers of shape (4, 5). Find the sum, mean, min, max, and standard deviation of the whole array.
# Then find the sum of each row and the sum of each column separately using the axis parameter. Print everything clearly labeled.


In [46]:
import numpy as np

twoDArray = np.random.randint(0,255, size = (4,5))
print("2D Array: " + "\n" + str(twoDArray))
print("Data Type: " + str(twoDArray.dtype))

Sum = np.sum(twoDArray)
Mean = np.mean(twoDArray)
Min = np.min(twoDArray)
Max = np.max(twoDArray)
Std = np.std(twoDArray)


print("Sum: " + str(Sum) + "\n" "Mean " + str(Mean) + "\n" + "Min: " + str(Min) + "\n" "Max " + str(Max) + "\n" + "Standard Deviation: " + str(Std))

# Axis Sums
columnSum = np.sum(twoDArray, axis = 0) # axis = 0 is column calculation | axis = 1 is row calculation
rowSum = np.sum(twoDArray, axis = 1) #Prints out a List of sums
i = 0
j = 0

for element in rowSum:
  print(f"Column {i}: " + str(element))
  i += 1
print("\n")
for element in columnSum:
  print(f"Row {j}: " + str(element))
  j += 1




2D Array: 
[[160 230 170 235 117]
 [250  93  10 242 195]
 [237  84 184   0 138]
 [  7  16 151  56 196]]
Data Type: int64
Sum: 2771
Mean 138.55
Min: 0
Max 250
Standard Deviation: 83.96813383659304
Column 0: 912
Column 1: 790
Column 2: 643
Column 3: 426


Row 0: 654
Row 1: 423
Row 2: 515
Row 3: 533
Row 4: 646


In [24]:
# Challenge 2 Create a 1D array of 20 random integers between 0 and 100. Write code that returns only the values greater than 50 without using a loop.
# Then replace all values less than 30 with zero. Print the array before and after.

In [61]:
array = np.random.randint(0, 100, size = (1, 20))
print("Before: " + "\n" +str(array) +"\n")
# Returns Values greater than 20

greaterValues = array[array > 50]

print("Values Above 50: " + str(greaterValues) +"\n")

array[array < 30] = 0
print("After: " + "\n" + str(array))

Before: 
[[28 32 79 79 28 80 44 52 19 74 23 65 45 11 69 16 66 79 72 95]]

Values Above 50: [79 79 80 52 74 65 69 66 79 72 95]

After: 
[[ 0 32 79 79  0 80 44 52  0 74  0 65 45  0 69  0 66 79 72 95]]


In [ ]:
# Challenge 3 Create two 2D arrays of shape (3, 4) and stack them both vertically and horizontally.
# Then take a (4, 6) array and split it into three equal parts along the column axis. Print the matrix of every result.

In [90]:
arrayOne = np.ones((3,4))
arrayTwo = np.zeros((3,4))

hStack = np.hstack([arrayOne, arrayTwo])
vStack = np.vstack([arrayOne, arrayTwo])

print(str(hStack) + "\n")
print(str(vStack) + "\n")

arrayThree = np.random.randint(1,5, size = (4,6)) # Split by 2 each time
print("Original Array: " + "\n" + str(arrayThree) + "\n")
exclude = 2 ## :2 | 2:4 | 4:
include = 0

while exclude <= 6:
  arraySplit = arrayThree[:, include:exclude]
  print(str(arraySplit) + "\n")
  include += 2
  exclude += 2

[[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Original Array: 
[[1 1 4 2 1 2]
 [2 1 1 1 1 2]
 [3 1 2 3 1 3]
 [3 4 1 2 1 2]]

[[1 1]
 [2 1]
 [3 1]
 [3 4]]

[[4 2]
 [1 1]
 [2 3]
 [1 2]]

[[1 2]
 [1 2]
 [1 3]
 [1 2]]



In [69]:
# Challenge 4 Create a (5, 5) array of random floats between 0 and 1.
# Normalize(Min-Max) it so every value falls between 0 and 255 as integers.

In [109]:
floatArray = np.random.random((5,5))
min = np.min(floatArray)
max = np.max(floatArray)
difference = (max - min)

normalizedArray = ((floatArray - min) / difference) * 255

print(normalizedArray)





[[  4.65817048 129.93685607 192.31374565  87.0538236  134.10247858]
 [184.76532284  76.77071325  79.38657291 215.65436369 133.08213181]
 [173.8010332   27.07511876 255.          74.34134131  84.66326897]
 [251.17877732  72.72688236 177.68757445 115.33886457  87.83322246]
 [242.89267918   0.          82.273339    95.34401725 129.96550535]]
